.TH combo 1 combo\-VERSION
.SH NAME
combo \- words combo generator.
.SH SYNOPSIS
.B combo
.RB [options]
.RB [words]
.SH DESCRIPTION

.SH OPTIONS
.TP
.BI \-a " maxwordsamount"
set words maximum to allocate memory for them.
.TP
.BI \-i " in_file"
get words from in_file either.
.TP
.BI \-m " m"
print only m-word repeated combinations.
.TP
.BI \-n " n"
print only n-word length combinations.
.TP
.BI \-o " out_file"
write output to the file.
.TP
.BI \-V
prints version information to standard output, then exits.
.TP
.BI \-s " seps"
add combinations where 'seps' characters are used to separate words in combinations.
.TP
.BI \-r
add reversed words to the list.
.TP
.BI \-+
get words from stdin either.

.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
