.TH combo 1 combo\-VERSION
.SH NAME
combo \- words combo generator.
.SH SYNOPSIS
.B combo
.RB [ \-v ]
.SH DESCRIPTION

.SH OPTIONS
.TP
.BI \-m " m"
print only m-word repeated combinations.
.TP
.B \-n " n"
print only n-word length combinations.
.TP
.BI \-o " file"
write output to the file.
.TP
.BI \-v
prints version information to standard output, then exits.
.TP
.BI \-s " seps"
add combinations where seps are used to separate words in combinations.
.TP
.BI \-r
add reversed words to the list.

.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
